default: &default
  adapter: mysql
  encoding: unicode
development:
  <<: *default
  adapter: mysql
  database: blog_app
  username: root
  password: Java@3002
  host: localhost
  port: 3306
  pool: 5
test:
  <<: *default
  adapter: mysql
  database: blog_app
  username: root
  password: Java@3002
  host: localhost
  port: 3306
  pool: 5